added lastRendered property to json indicies
WycliffeAssociates/ScriptureRenderingPipeline pull request #63
Opened 2023-03-15 22:07 UTC by wkelly17

@rbnswartz  @PurpleGuitar 

This is one more additional PR on top of #61. (I merged 61 into dev, but not master, hence it's not killed yet).  I Just accidentally originally wrote that PR to master instead of develop.  I'll kill that when this is approved/when Read on Web is ready to consume it.  
These two commits do two things. 
1. Adds a lastRendered property to several models.   At the moment, I don't have any way of doing any sort of cache invalidation even if I wanted to for read on Web.  Adding a timestamp should enable cache invalidation if needed (which would be nice to put into the live reader since there is some measure of it caching things in its service worker.
2.  I added the total Byte count to the index.json file as well.  I realized it made more sense there than only in the download file.  That way someone can know how much is going to come across the wire if they do want to save the whole thing to their browser's cache.

2023-03-16 17:56 UTC, rbnswartz commented
@wkelly17 Let's merge in #61 and then you'll need to rebase on top of that

2023-03-16 19:27 UTC, rbnswartz requested changes
The only thing I'm really blocking on is the inconsitent naming of timestamp field. I feel as if we're duplicating information by having byte counts in both indexes, and I don't particularly like using unix timestamps. But I assume you have a reason for using those?

2023-03-16 19:27 UTC, rbnswartz commented on ScriptureRenderingPipeline/Models/OutputBook.cs
> +	[JsonPropertyName("lastRendered")]
I don't really like using unix timestamps, it is going to make trying to figure out what is going wrong with something in the future when we're looking at the output files. But if we have a reason why it should be a timestamp we should go for it but if not then we should consider using a normal date.

2023-03-16 19:35 UTC, wkelly17 commented on ScriptureRenderingPipeline/Models/OutputBook.cs
> +	[JsonPropertyName("lastRendered")]
Yes.  In JS new Date(unixMs) gives you a date object (but you can also feed it several versions of timestrings really). And I know languages/environments have trouble with serializing Dates, so I figured a scalar value was simplest and you can compare Unix MS without any conversions.  I can just say, is what unix timestamp cached smaller than or equal to the one in the current index? I'm plenty amenable to something else though.  A dd/mm/yyyy string works just as well for me.  (comparing the two strings is a litttle more work, but still not that big of a deal). Just let me know if you do want to switch it for sure.

2023-03-16 19:38 UTC, wkelly17 commented on ScriptureRenderingPipeline/Models/OutputBook.cs
> +	[JsonPropertyName("lastRendered")]
I'm fine with pulling out the byte count of the download index.  I'd rather it be in the primary index which is where it make more sense.  I'll change that.

2023-03-17 15:42 UTC, wkelly17 commented
@rbnswartz [6903c43](https://github.com/WycliffeAssociates/ScriptureRenderingPipeline/pull/63/commits/6903c431e12c98a26f8e8af4768396fdbda33205) Changes to iso8601 timestamps and pulls out the bytecount duplication  by only leaving it in the primary output index.json.  Lemme know if you have any other concerns here.

2023-03-17 16:55 UTC, PurpleGuitar commented on ScriptureRenderingPipeline/Models/OutputBook.cs
> +	[JsonPropertyName("lastRendered")]
I recommend using ISO format -- it sorts and compares correctly and is human readable.

2011-10-05T14:48:00.000Z

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString

2023-03-17 16:56 UTC, PurpleGuitar approved these changes

2023-03-17 19:23 UTC, merged